import paramiko as p
client=p.SSHClient()
#to access the host automatically->
client.set_missing_host_key_policy(p.AutoAddPolicy)
client.connect('test.rebex.net',username='demo',password='password',port=22)
print("connection successful")
stdin,out,err=client.exec_command('ls')
cmd_out=out.read()
print('cmd_out=',cmd_out)

ftp=client.open_sftp()
ftp_out=ftp.get('readme.txt','ftp_readme.txt')
print('ftp_out=',ftp_out)
#to put the value of a file into this file
ftp.put('out1.txt','out1.txt')#access will be denied as it is a public server, they wont allow us to have the file


o/p:

"C:\Users\lab365\Desktop\Python programming\myvenv1\Scripts\python.exe" "C:/Users/lab365/Desktop/Python programming/bin/ssh.py"
connection successful
cmd_out= b'aspnet_client\npub\nreadme.txt\n'
ftp_out= None
Traceback (most recent call last):
  File "C:/Users/lab365/Desktop/Python programming/bin/ssh.py", line 15, in <module>
    ftp.put('out1.txt','out1.txt')
  File "C:\Users\lab365\Desktop\Python programming\myvenv1\lib\site-packages\paramiko\sftp_client.py", line 759, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "C:\Users\lab365\Desktop\Python programming\myvenv1\lib\site-packages\paramiko\sftp_client.py", line 714, in putfo
    with self.file(remotepath, "wb") as fr:
  File "C:\Users\lab365\Desktop\Python programming\myvenv1\lib\site-packages\paramiko\sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "C:\Users\lab365\Desktop\Python programming\myvenv1\lib\site-packages\paramiko\sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "C:\Users\lab365\Desktop\Python programming\myvenv1\lib\site-packages\paramiko\sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "C:\Users\lab365\Desktop\Python programming\myvenv1\lib\site-packages\paramiko\sftp_client.py", line 896, in _convert_status
    raise IOError(errno.EACCES, text)
PermissionError: [Errno 13] Access denied.

Process finished with exit code 1
